# Generated by Django 5.2.12 on 2026-04-05 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('breeds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sheep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.CharField(max_length=50, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('purchase_type', models.CharField(choices=[('Born At Farm', 'Born At Farm'), ('Purchased', 'Purchased')], max_length=20)),
                ('remark', models.TextField(blank=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_weight', models.FloatField(blank=True, null=True)),
                ('mother_tag', models.CharField(blank=True, max_length=50)),
                ('father_tag', models.CharField(blank=True, max_length=50)),
                ('birth_type', models.CharField(blank=True, choices=[('Single', 'Single'), ('Twin', 'Twin'), ('Triplet', 'Triplet'), ('Quadruplet', 'Quadruplet')], max_length=20)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_price', models.FloatField(blank=True, null=True)),
                ('age_months', models.IntegerField(blank=True, null=True)),
                ('vendor_name', models.CharField(blank=True, max_length=100)),
                ('breed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='breeds.breed')),
            ],
        ),
    ]
